version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - baby_tracker_network
    ports:
      - 80:80

  web:
    image: baby_tracker:v1.06
    build: .
    networks:
      baby_tracker_network:
        aliases:
          - tracker-site
    ports:
      - 8080:8080
    restart: always

networks:
  baby_tracker_network: